### ISSUE TITLE
Feature request: Communication protocol

### ISSUE THREAD

**Issue by Highcooley** [Emile666/stc1000_stm8#4]
Could you please implement a communication protocol like Mats did on the pic version to read/write temperature as well as settings with an external controller? I plan to attach an IoT controller for remote control purposes, logging as well as having a graphical UI.

**Comment by Emile666** [comment]
This is difficult to do for two reasons:
1) Hardware. The stock microcontroller has an UART connected to PD5 (UART1_TX) and PD6 (UART1_RX). Both pins are currently in use. If you give up the buzzer (now connected to PD6) and the new PID/SSR feature, you could implement this. In my opinion, the PID/SSR functionality is more useful than UART communication. But still: you need a new frontpanel PCB and that's not what most people are willing to do for this project.
2) Software. We only have 8K and pretty much everything is taken, since I already added most of Mats separate options in this firmware. UART communication with a command-interpreter is pretty substantial and would not fit in the remaining flash memory.

So: not feasible with the current hardware and software. But have a look at my other project: 'stc1000p on steroids'. That one has UART communications (and lots of other stuff).
