### ISSUE TITLE
PID output decimal dot

### ISSUE THREAD

**Issue by zstomp** [Emile666/stc1000_stm8#5]
In PID output display mode (PWR button pressed twice), decimal dot is not showing. I think it would be less confusing if it showed.

**Comment by Emile666** [comment]
Good point! Initially I calculated pid_output as a percentage, but since all temperatures are in E-1 °C, it was more convenient to also calculate pid_out in E-1 (%). I can do two things:
- Drop the E-1 % and display pid_out in %
- Display it as E-1 % with a dot (e.g. 85.3) and display 100 % as '100'
Any comments on these two options? What do you prefer?

**Comment by zstomp** [comment]
I think I'm a little bit more inclined towards second option. And thanks for the awesome firmware!

**Comment by Emile666** [comment]
Thanks! The call to display the PID output percentage is given in stc1000p.c, line 425. Replace LEDS_TEMP with a new define (e.g. LEDS_PERC).
In stc1000p_lib.c, lines 170-200, the value_to_led() function is given. This function needs to be updated to also display a percentage.
